Selecting class
zhamilto/AttendanceTracker pull request #4
Opened 2023-04-25 21:20 UTC by eperrio1

2023-04-25 22:00 UTC, WhonixJosh requested changes

2023-04-25 22:00 UTC, WhonixJosh commented on src/main/java/AttendanceTracker/App.java
> +        System.out.println("\nCourses offered in the Fall");
Move this to a function

2023-04-25 22:00 UTC, WhonixJosh commented on src/main/java/AttendanceTracker/App.java
> +        System.out.println("\nSelect a course: ");
this needs to handle input mismatch exception if I input a non-string

2023-04-25 22:00 UTC, WhonixJosh commented on src/main/java/AttendanceTracker/App.java
> +        System.out.println("\nSelect a course: ");
Move this to separate class outside of the App in main.java

2023-04-25 22:00 UTC, WhonixJosh commented on src/test/java/AttendanceTracker/AppTest.java
> +        assertEquals("MATH 1234", App.selectingClass(mockList));
add a failing test

2023-04-25 22:00 UTC, WhonixJosh commented on src/test/java/AttendanceTracker/AppTest.java
> +    @Test void testselectingClass() {
Refactor the tested methods into a new class with the tests in a separate test file

2023-04-25 22:00 UTC, WhonixJosh commented on src/main/java/AttendanceTracker/App.java
> +            myObj = new Scanner(System.in);
Don't forget to close the scanner, wrap this in a try{}finally{scanner.close()}

2023-04-27 04:51 UTC, eperrio1 commented on src/main/java/AttendanceTracker/App.java
> +        System.out.println("\nCourses offered in the Fall");
This is only temporary to see if my code work. The real function will be written once we do the "On the class view, the user can click the "Display List of Courses" button to see a list of every class for the given semester and year" user story.

2023-04-27 20:23 UTC, merged